using System;
using System.Collections.Generic;
using System.Text;

namespace ProtoBufSerialization.Model
{
    // <auto-generated>
    //   This file was generated by a tool; you should avoid making direct changes.
    //   Consider using 'partial classes' to extend these types
    //   Input: my.proto
    // </auto-generated>

    #region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
    [global::ProtoBuf.ProtoContract()]
    public partial class ArrayNode : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"data")]
        public byte[] Data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReserveIP : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string deviceName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"MAC")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Mac { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"IP")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ip { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StaticRoute : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string destIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string subnetMask { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string defaultGateway { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class WlanFilter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string deviceName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"MAC")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Mac { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Client : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool isOnline { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ConnectType connectType { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clientName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"MAC")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Mac { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string IPv4 { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string IPv6 { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public uint dhcpRemainDay { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public uint dhcpRemainHour { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public uint dhcpRemainMinute { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public uint allowInternet { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum ConnectType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"WIRED")]
            Wired = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"WIRELESS")]
            Wireless = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActionInModifyWebPassword : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string oldPassword { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string newPassword { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActionOutModifyWebPassword : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActionInDeviceReboot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActionOutDeviceReboot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActionInDeviceRestore : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ActionOutDeviceRestore : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MacFilter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clientName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"MAC")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Mac { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class IpFilter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string wanIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public Protocal protocal { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint wanStartPort { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint wanEndPort { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clientName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string lanIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        public uint lanStartPort { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public uint lanEndPort { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Protocal
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ALL_PROTOCAL")]
            AllProtocal = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TCP_PROTOCAL")]
            TcpProtocal = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"UDP_PROTOCAL")]
            UdpProtocal = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TCP_UDP_PROTOCAL")]
            TcpUdpProtocal = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ICMP_PROTOCAL")]
            IcmpProtocal = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DomainFilter : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VirtualServer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public Protocal protocal { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint wanStartPort { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint wanEndPort { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string lanIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        public uint lanStartPort { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public uint lanEndPort { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Protocal
        {
            [global::ProtoBuf.ProtoEnum(Name = @"ALL_PROTO")]
            AllProto = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TCP_PROTO")]
            TcpProto = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"UDP_PROTO")]
            UdpProto = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UsbShareAccount : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"account")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Account { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RouterProperties : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public EthwanLinkStatus ethwanLinkStatus { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ethwanMAC { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ethwanIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ethwanSubnet { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ethwanGateway { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ethwanPrimaryDNS { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string ethwanSecondaryDNS { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8)]
        public uint onlineClientNo { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public ConnectMode connectMode { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string pppoeAccount { get; set; } = "";

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string pppoePassword { get; set; } = "";

        [global::ProtoBuf.ProtoMember(12)]
        public uint pppoeMTU { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public bool dynamicManualDnsEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dynamicManualPrimaryDNS { get; set; } = "";

        [global::ProtoBuf.ProtoMember(15)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dynamicManualSecondaryDNS { get; set; } = "";

        [global::ProtoBuf.ProtoMember(16)]
        public uint dynamicMTU { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        [global::System.ComponentModel.DefaultValue("")]
        public string staticIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(18)]
        [global::System.ComponentModel.DefaultValue("")]
        public string staticSubnet { get; set; } = "";

        [global::ProtoBuf.ProtoMember(19)]
        [global::System.ComponentModel.DefaultValue("")]
        public string staticGateway { get; set; } = "";

        [global::ProtoBuf.ProtoMember(20)]
        [global::System.ComponentModel.DefaultValue("")]
        public string staticPrimaryDNS { get; set; } = "";

        [global::ProtoBuf.ProtoMember(21)]
        [global::System.ComponentModel.DefaultValue("")]
        public string staticSecondaryDNS { get; set; } = "";

        [global::ProtoBuf.ProtoMember(22)]
        public uint staticMTU { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        [global::System.ComponentModel.DefaultValue("")]
        public string lanIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(24)]
        [global::System.ComponentModel.DefaultValue("")]
        public string lanSubnet { get; set; } = "";

        [global::ProtoBuf.ProtoMember(25)]
        public bool dhcpEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dhcpStartIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(27)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dhcpEndIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(28)]
        public bool dhcpManualDNSEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(29)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dhcpManualDNSPrimary { get; set; } = "";

        [global::ProtoBuf.ProtoMember(30)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dhcpManualDNSSecondary { get; set; } = "";

        [global::ProtoBuf.ProtoMember(31)]
        public uint dhcpLeaseTime { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"reserveIP")]
        public global::System.Collections.Generic.List<ArrayNode> reserveIPs { get; } = new global::System.Collections.Generic.List<ArrayNode>();

        [global::ProtoBuf.ProtoMember(33, Name = @"staticRoute")]
        public global::System.Collections.Generic.List<ArrayNode> staticRoutes { get; } = new global::System.Collections.Generic.List<ArrayNode>();

        [global::ProtoBuf.ProtoMember(34)]
        public bool wlanEnabled2p4g { get; set; }

        [global::ProtoBuf.ProtoMember(35, Name = @"ssid2p4g")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ssid2p4g { get; set; } = "";

        [global::ProtoBuf.ProtoMember(36)]
        public bool hideSsidEnabled2p4g { get; set; }

        [global::ProtoBuf.ProtoMember(37)]
        public SercurityMode sercurityMode2p4g { get; set; }

        [global::ProtoBuf.ProtoMember(38, Name = @"password2p4g")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password2p4g { get; set; } = "";

        [global::ProtoBuf.ProtoMember(39)]
        public TransmitPower transmitPower2p4g { get; set; }

        [global::ProtoBuf.ProtoMember(40)]
        public bool wlanEnabled5g { get; set; }

        [global::ProtoBuf.ProtoMember(41, Name = @"ssid5g")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ssid5g { get; set; } = "";

        [global::ProtoBuf.ProtoMember(42)]
        public bool hideSsidEnabled5g { get; set; }

        [global::ProtoBuf.ProtoMember(43)]
        public SercurityMode sercurityMode5g { get; set; }

        [global::ProtoBuf.ProtoMember(44, Name = @"password5g")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password5g { get; set; } = "";

        [global::ProtoBuf.ProtoMember(45)]
        public TransmitPower transmitPower5g { get; set; }

        [global::ProtoBuf.ProtoMember(46)]
        public bool priorityEnabled5g { get; set; }

        [global::ProtoBuf.ProtoMember(47)]
        [global::System.ComponentModel.DefaultValue("")]
        public string combinedSSID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(48)]
        public SercurityMode combinedSercurityMode { get; set; }

        [global::ProtoBuf.ProtoMember(49)]
        [global::System.ComponentModel.DefaultValue("")]
        public string combinedPassword { get; set; } = "";

        [global::ProtoBuf.ProtoMember(50)]
        public bool hideCombinedEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(51)]
        public bool guestWlanEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(52)]
        [global::System.ComponentModel.DefaultValue("")]
        public string guestWlanSSID { get; set; } = "";

        [global::ProtoBuf.ProtoMember(53)]
        public uint guestWlanTime { get; set; }

        [global::ProtoBuf.ProtoMember(54)]
        public SercurityMode guestWlanSercurityMode { get; set; }

        [global::ProtoBuf.ProtoMember(55)]
        [global::System.ComponentModel.DefaultValue("")]
        public string guestWlanPassword { get; set; } = "";

        [global::ProtoBuf.ProtoMember(56)]
        public bool guestWlanBroadcastEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(57)]
        public bool wlanFilterEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(58)]
        public FilterType wlanFilterType { get; set; }

        [global::ProtoBuf.ProtoMember(59, Name = @"wlanFilter")]
        public global::System.Collections.Generic.List<ArrayNode> wlanFilters { get; } = new global::System.Collections.Generic.List<ArrayNode>();

        [global::ProtoBuf.ProtoMember(60)]
        public bool wpsEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(61, Name = @"client")]
        public global::System.Collections.Generic.List<ArrayNode> Clients { get; } = new global::System.Collections.Generic.List<ArrayNode>();

        [global::ProtoBuf.ProtoMember(62)]
        [global::System.ComponentModel.DefaultValue("")]
        public string webPassword { get; set; } = "";

        [global::ProtoBuf.ProtoMember(66)]
        public bool firewallEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(67)]
        public bool macFilterEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(68)]
        public FilterType macFilterType { get; set; }

        [global::ProtoBuf.ProtoMember(69, Name = @"macFilter")]
        public global::System.Collections.Generic.List<ArrayNode> macFilters { get; } = new global::System.Collections.Generic.List<ArrayNode>();

        [global::ProtoBuf.ProtoMember(70)]
        public bool ipFilterEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(71)]
        public FilterType ipFilterType { get; set; }

        [global::ProtoBuf.ProtoMember(72, Name = @"ipFilter")]
        public global::System.Collections.Generic.List<ArrayNode> ipFilters { get; } = new global::System.Collections.Generic.List<ArrayNode>();

        [global::ProtoBuf.ProtoMember(73)]
        public bool domainFilterEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(74, Name = @"domainFilter")]
        public global::System.Collections.Generic.List<ArrayNode> domainFilters { get; } = new global::System.Collections.Generic.List<ArrayNode>();

        [global::ProtoBuf.ProtoMember(75)]
        public bool dmzEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(76)]
        [global::System.ComponentModel.DefaultValue("")]
        public string dmzIP { get; set; } = "";

        [global::ProtoBuf.ProtoMember(77, Name = @"virtualServer")]
        public global::System.Collections.Generic.List<ArrayNode> virtualServers { get; } = new global::System.Collections.Generic.List<ArrayNode>();

        [global::ProtoBuf.ProtoMember(78)]
        public bool upnpEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(79)]
        public bool usbShareEnabled { get; set; }

        [global::ProtoBuf.ProtoMember(80)]
        public UsbShareAccount usbShareAccount { get; set; }

        [global::ProtoBuf.ProtoMember(81)]
        public bool priorityWifiEnabled5g { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EthwanLinkStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNCONNECTED")]
        Unconnected = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CONNECTING")]
        Connecting = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CONNECTED")]
        Connected = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ConnectMode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ONLY_LAN")]
        OnlyLan = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DYNAMIC_IP")]
        DynamicIp = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PPPOE")]
        Pppoe = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"STATIC_IP")]
        StaticIp = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum SercurityMode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NO_ENCRYPTION")]
        NoEncryption = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"WPA_WPA2_PSK")]
        WpaWpa2Psk = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WPA2_PSK")]
        Wpa2Psk = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"WPA3_SAE")]
        Wpa3Sae = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum TransmitPower
    {
        [global::ProtoBuf.ProtoEnum(Name = @"STD")]
        Std = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STRONG")]
        Strong = 1,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum FilterType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ALLOW")]
        Allow = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FORBID")]
        Forbid = 1,
    }

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
    #endregion

}
